import { ArrowUpRight, ChevronRight, Search, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { articles, characters, medals, popularSearches, updates } from '@/data/mockData';
import { CharacterCard, GuideShell, MedalCard, SectionHeader, SidebarCard } from '@/components/guide-shell';

export default function HomePage() {
  return <GuideShell><div className="animate-enter">
    <section className="relative overflow-hidden rounded-md bg-sidebar px-6 py-9 text-white shadow-card-lg sm:px-10 sm:py-12">
      <div className="absolute right-0 top-0 h-full w-1/2 opacity-20" style={{ backgroundImage: 'linear-gradient(115deg, transparent 48%, #4b9de9 49%, transparent 50%), linear-gradient(65deg, transparent 48%, #4b9de9 49%, transparent 50%)', backgroundSize: '44px 44px' }} />
      <div className="relative max-w-2xl"><div className="data-label mb-5 text-sky-300">THE DEFINITIVE GAME GUIDE / 2024.06</div><h1 className="text-balance text-3xl font-black leading-[1.2] tracking-tight sm:text-5xl">勝つための情報を、<br /><span className="text-sky-300">最短距離</span>で。</h1><p className="mt-5 max-w-lg text-sm leading-7 text-slate-300">キャラクター、メダル、編成データを一つに。覇道を進むプレイヤーのための、実戦型データベース。</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/characters" className="flex items-center gap-2 rounded-sm bg-primary px-4 py-2.5 text-xs font-bold text-white hover:bg-blue-500" data-testid="link-hero-characters">キャラクターを探す <ChevronRight size={15} /></Link><Link href="/support" className="flex items-center gap-2 rounded-sm border border-white/20 bg-white/5 px-4 py-2.5 text-xs font-bold text-white hover:bg-white/10" data-testid="link-hero-builder">編成を組む <ArrowUpRight size={14} /></Link></div></div>
      <div className="absolute bottom-5 right-8 hidden text-right lg:block"><div className="font-data text-7xl font-semibold leading-none text-white/10">HADO</div><div className="font-data text-[10px] tracking-[.4em] text-sky-300/70">FIELD MANUAL</div></div>
    </section>

    <div className="mt-8 grid gap-8 xl:grid-cols-[minmax(0,1fr)_300px]">
      <div className="min-w-0">
        <SectionHeader eyebrow="QUICK ACCESS" title="今、調べられているデータ" />
        <div className="grid gap-3 sm:grid-cols-2">
          <QuickSearch label="キャラクター" value="黒鉄 蘭" meta="評価 / 編成 / スキル" href="/characters/kurogane-ran" />
          <QuickSearch label="メダル" value="月華の調べ" meta="効果 / 相性 / 入手方法" href="/medals/gekka-no-shirabe" />
        </div>
        <div className="mt-9"><SectionHeader eyebrow="FEATURED" title="注目キャラクター" href="/characters" /><div className="grid gap-3 md:grid-cols-2">{characters.slice(0, 4).map((character) => <CharacterCard key={character.id} character={character} />)}</div></div>
        <div className="mt-9"><SectionHeader eyebrow="LATEST ARTICLES" title="最新記事" href="/strategy" /><div className="space-y-2">{articles.slice(0, 2).map((article) => <Link key={article.id} href="/strategy" className="interactive-card flex items-center justify-between rounded-md border border-card-border bg-card p-4 shadow-card"><div><div className="text-[10px] font-bold text-primary">{article.type} <span className="ml-2 font-data text-muted-foreground">{article.date}</span></div><h3 className="mt-1 text-sm font-black">{article.title}</h3></div><ChevronRight size={15} className="shrink-0 text-muted-foreground" /></Link>)}</div></div>
        <div className="mt-9"><SectionHeader eyebrow="LATEST DATABASE" title="メダルピックアップ" href="/medals" /><div className="grid gap-3 md:grid-cols-2">{medals.slice(0, 4).map((medal) => <MedalCard key={medal.id} medal={medal} />)}</div></div>
        <div className="mt-9 grid gap-8 md:grid-cols-2"><div><SectionHeader eyebrow="CHARACTER RANKING" title="キャラクターランキング" href="/rankings" /><div className="space-y-2">{characters.slice(0, 3).map((character, index) => <Link key={character.id} href={`/characters/${character.id}`} className="flex items-center gap-3 rounded-md border border-card-border bg-card p-3 shadow-card"><span className="font-data w-5 text-center text-sm font-bold text-primary">{index + 1}</span><span className="flex-1 text-xs font-black">{character.name}</span><span className="font-data text-sm font-bold text-primary">{character.tier}</span></Link>)}</div></div><div><SectionHeader eyebrow="MEDAL RANKING" title="メダルランキング" href="/rankings" /><div className="space-y-2">{medals.slice(0, 3).map((medal, index) => <Link key={medal.id} href={`/medals/${medal.id}`} className="flex items-center gap-3 rounded-md border border-card-border bg-card p-3 shadow-card"><span className="font-data w-5 text-center text-sm font-bold text-primary">{index + 1}</span><span className="flex-1 text-xs font-black">{medal.name}</span><span className="text-[10px] text-muted-foreground">{medal.category}</span></Link>)}</div></div></div>
      </div>
      <aside className="space-y-5">
        <SidebarCard title="データ更新履歴"><div className="space-y-4">{updates.slice(0, 4).map((item) => <div key={item.date} className="flex gap-3"><span className="font-data text-[10px] text-primary">{item.date}</span><div><p className="text-xs font-bold leading-5">{item.title}</p><span className="text-[10px] text-muted-foreground">{item.category}</span></div></div>)}</div><Link href="/mypage" className="mt-4 flex items-center justify-center gap-1 border-t border-border pt-3 text-[10px] font-bold text-primary" data-testid="link-update-history">更新履歴を見る <ChevronRight size={13} /></Link></SidebarCard>
        <SidebarCard title="人気記事"><div className="space-y-3">{articles.map((article, index) => <Link key={article.id} href="/strategy" className="flex gap-3"><span className="font-data text-xs font-bold text-primary">{String(index + 1).padStart(2, '0')}</span><span className="text-xs font-bold leading-5">{article.title}</span></Link>)}</div></SidebarCard>
        <SidebarCard title="よく検索されるワード"><div className="flex flex-wrap gap-2">{popularSearches.map((item) => <Link key={item} href={`/characters?search=${encodeURIComponent(item)}`} className="rounded-sm border border-border bg-background px-2 py-1.5 text-[10px] font-bold text-muted-foreground hover:border-primary hover:text-primary" data-testid={`link-popular-${item}`}>{item}</Link>)}</div></SidebarCard>
        <div className="rounded-md border border-primary/20 bg-blue-50 p-4"><div className="flex items-center gap-2 text-primary"><Sparkles size={16} /><h3 className="text-sm font-black">サポート編成を試す</h3></div><p className="mt-2 text-xs leading-5 text-blue-900/70">手持ちのキャラクターから、目的に合った編成候補を自動で組み立てます。</p><Link href="/support" className="mt-3 flex items-center gap-1 text-xs font-bold text-primary" data-testid="link-sidebar-builder">ビルダーを開く <ChevronRight size={13} /></Link></div>
      </aside>
    </div>
  </div></GuideShell>;
}

function QuickSearch({ label, value, meta, href }: { label: string; value: string; meta: string; href: string }) {
  return <Link href={href} className="interactive-card flex items-center justify-between rounded-md border border-card-border bg-card p-4 shadow-card" data-testid={`link-quick-${value}`}><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-sm bg-secondary text-primary">{label === 'メダル' ? <Sparkles size={17} /> : <Search size={17} />}</div><div><span className="text-[10px] text-muted-foreground">{label}</span><p className="text-sm font-black">{value}</p><span className="text-[10px] text-muted-foreground">{meta}</span></div></div><ArrowUpRight size={16} className="text-muted-foreground" /></Link>;
}