import { useMemo, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { medals } from '@/data/mockData';
import { EmptyState, GuideShell, MedalCard, PageIntro, SidebarCard } from '@/components/guide-shell';

export default function MedalsPage() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('すべて');
  const filtered = useMemo(() => medals.filter((item) => `${item.name}${item.effect}${item.tags.join('')}`.includes(query) && (category === 'すべて' || item.category === category)), [query, category]);
  return <GuideShell><PageIntro eyebrow="MEDAL DATABASE" title="メダル" description="効果を比較して、キャラクターの強みをさらに伸ばす一枚を選ぶ。" action={<div className="hidden items-center gap-2 text-right sm:flex"><span className="font-data text-2xl font-semibold text-primary">{filtered.length}</span><span className="text-[10px] text-muted-foreground">MEDALS</span></div>} /><div className="grid gap-8 xl:grid-cols-[minmax(0,1fr)_240px]"><div><div className="flex items-center gap-2 rounded-md border border-card-border bg-card p-3 shadow-card"><Search size={16} className="text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="メダル名、効果、タグで検索" className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground/70" data-testid="input-medal-search" /></div>{filtered.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{filtered.map((medal) => <MedalCard key={medal.id} medal={medal} />)}</div> : <div className="mt-4"><EmptyState label="条件に一致するメダルが見つかりません" /></div>}</div><aside><SidebarCard title="カテゴリ"><div className="space-y-1">{['すべて', '攻撃強化', '防御強化', '速度強化', '状態異常', '妨害', '回復支援'].map((item) => <button key={item} onClick={() => setCategory(item)} className={`flex w-full items-center justify-between rounded-sm px-2.5 py-2 text-left text-xs font-bold ${category === item ? 'bg-primary text-white' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`} data-testid={`button-medal-category-${item}`}>{item}<span className="font-data text-[10px]">{item === 'すべて' ? medals.length : medals.filter((medal) => medal.category === item).length}</span></button>)}</div><button onClick={() => { setQuery(''); setCategory('すべて'); }} className="mt-4 flex w-full items-center justify-center gap-2 border-t border-border pt-3 text-[10px] font-bold text-muted-foreground hover:text-primary" data-testid="button-reset-medal-filter"><SlidersHorizontal size={13} />条件をリセット</button></SidebarCard></aside></div></GuideShell>;
}